from pathlib import Path
import re

BASE = Path(__file__).resolve().parent.parent
RESULTS = BASE / "results"
REPORT = RESULTS / "performance-report.md"

rows = []

for file in sorted(RESULTS.glob("*.txt")):
    text = file.read_text()

    records = re.search(r"(?:Records|Records Read):\s*(\d+)", text)
    elapsed = re.search(r"Elapsed:\s*([\d.]+)\s*s", text)
    cpu = re.search(r"CPU:\s*([\d.]+)%", text)

    if records and elapsed:
        rows.append({
            "name": file.stem,
            "records": int(records.group(1)),
            "elapsed": float(elapsed.group(1)),
            "cpu": float(cpu.group(1)) if cpu else None
        })

print("=" * 62)
print("          COBOL MAINFRAME PERFORMANCE ANALYZER")
print("=" * 62)

for row in rows:
    cpu = f"{row['cpu']:.0f}%" if row["cpu"] is not None else "N/A"

    print(
        f"{row['name']:<22} "
        f"Records: {row['records']:>10,}  "
        f"Elapsed: {row['elapsed']:>6.2f}s  "
        f"CPU: {cpu}"
    )

print("=" * 62)

report = [
    "# COBOL Mainframe Performance Lab — Performance Report",
    "",
    "Automated benchmark summary generated by the Python Analyzer.",
    "",
    "| Experiment | Records | Elapsed | CPU |",
    "|---|---:|---:|---:|"
]

for row in rows:
    cpu = f"{row['cpu']:.0f}%" if row["cpu"] is not None else "N/A"

    report.append(
        f"| {row['name']} | "
        f"{row['records']:,} | "
        f"{row['elapsed']:.2f}s | "
        f"{cpu} |"
    )

report += [
    "",
    "## Experiments",
    "",
    "- Baseline CPU workload",
    "- 50 million record CPU workload",
    "- 100 thousand record batch + file I/O workload",
    "- 1 million record batch + file I/O workload",
    "",
    "## Environment",
    "",
    "- COBOL: GnuCOBOL 3.2.0",
    "- Automation: Python 3",
    "- Platform: Linux / WSL2",
    "",
    "## Purpose",
    "",
    "This laboratory evaluates COBOL batch-processing behavior "
    "through repeatable workloads, operating-system measurements "
    "and automated result analysis."
]

REPORT.write_text("\n".join(report) + "\n")

print(f"Report generated: {REPORT}")
